services:
    oracle-db:
        image: container-registry.oracle.com/database/free:23.8.0.0
        container_name: oracle-apex-db
        ports:
          - "1521:1521"
          - "5500:5500"
        environment:
          ORACLE_PWD: Oracle123
        volumes:
          - oracle-data:/opt/oracle/oradata
        restart: unless-stopped

volumes:
  oracle-data:

